# syntax = docker/dockerfile:experimental
FROM oaktreetech/orthanc-s3:latest
ARG CI_COMMIT_SHA

# Install Python Requests Module
RUN pip3 install requests

# Install Sonador Python Plugin
RUN mkdir -p /opt/orthanc/
RUN export CI_COMMIT_SHA=${CI_COMMIT_SHA:-master} \
  && echo "Build container for Sonador/Orthanc Plugin $CI_COMMIT_SHA" \
  && cd /opt/orthanc/ \
  && git clone https://code.oak-tree.tech/oak-tree/medical-imaging/orthanc-sonador.git \
  && cd orthanc-sonador && git checkout $CI_COMMIT_SHA \
  && git submodule update --init --recursive --remote \
  && pip3 install --timeout 30 -r requirements.txt
