FROM osimis/orthanc:22.10.1-full

# The Osimis "full" image contains all cloud storage plugins along
ARG CI_COMMIT_SHA

# Install Python Requests Module
RUN apt-get update
RUN apt-get install -y python3-requests libtiff5-dev libjpeg-dev zlib1g-dev \
  libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev \
  tcl8.6-dev tk8.6-dev python-tk git librdkafka-dev

# Install Sonador Python Plugin
RUN mkdir -p /opt/orthanc/
RUN export CI_COMMIT_SHA=${CI_COMMIT_SHA:-master} \
  && echo "Build container for Sonador/Orthanc Plugin $CI_COMMIT_SHA" \
  && cd /opt/orthanc/ \
  && git clone https://code.oak-tree.tech/oak-tree/medical-imaging/orthanc-sonador.git \
  && cd orthanc-sonador && git checkout $CI_COMMIT_SHA \
  && git submodule update --init --recursive --remote \
  && pip3 install --timeout 300 -r requirements.txt
