import json, logging, uuid, traceback
import orthanc

from sonador.apisettings import DicomDatetimePairKey, \
	IMAGING_SERVER_RESOURCE_IMAGE, IMAGING_SERVER_RESOURCE_SERIES, IMAGING_SERVER_RESOURCE_STUDY, IMAGING_SERVER_RESOURCE_PATIENT, \
	IMAGING_SERVER_RESOURCE_SUPPORTED, DCMHEADER_SERIES_INSTANCE_UID, DCMHEADER_STUDY_ID, DCMHEADER_PATIENT_ID, IMAGING_SERVER_UID_REGEX, \
	DCMHEADER_MODALITY, DCM_MODALITY_SR, DCMHEADER_SR_PERTINENT_OTHER_EVIDENCE_SEQUENCE, DCMHEADER_SR_REF_SERIES_SEQ, \
	DCMHEADER_SR_CONTENT_SEQUENCE

from ..apisettings import KAFKA_TIMEOUT_DEFAULT, ORTHANC_CONFIG_SECTION_SONADOR, SONADOR_CONF_KAFKA, \
	SONADOR_CONF_KAFKA_SERVERS, SONADOR_CONF_KAFKA_TOPIC, SONADOR_KAFKA_BOOTSTRAP, \
	ORTHANC_SERVER_ID as KTAG_ORTHANC_SERVER_ID, \
	ORTHANC_SERVER_RESOURCE as KTAG_ORTHANC_SERVER_RESOURCE, \
	ORTHANC_SERVER_SOURCE as KTAG_ORTHANC_SERVER_SOURCE, \
	ORTHANC_SERVER_DICOM as KTAG_ORTHANC_SERVER_DICOM

from ..db.comments import ImagingSeriesComment
from ..validation.comments import CommentValidationForm

logger = logging.getLogger(__name__)

COMMENT_TEMPLATE_DEFAULT = 'DICOM-SR Meta: SR-ID=%(ID)s, SR-DCMUID=%(SeriesInstanceUID)s)'

