from sonador.apisettings import \
	IMAGING_SERVER_RESOURCE_PATIENT, IMAGING_SERVER_RESOURCE_STUDY, IMAGING_SERVER_RESOURCE_SERIES, \
	DCMHEADER_PATIENT_NAME, DCMHEADER_PATIENT_ID, DCMHEADER_PATIENT_BIRTHDATE, \
	DCMHEADER_PATIENT_SEX, DCMHEADER_PATIENT_OTHERIDS, \
	DCMHEADER_STUDY_DATE, DCMHEADER_STUDY_TIME, DCMHEADER_STUDY_ID, \
	DCMHEADER_STUDY_DESCRIPTION, DCMHEADER_ACCESSION_NUMBER, DCMHEADER_STUDY_INSTANCE_UID, \
	DCMHEADER_REQUESTED_PROCEDURE_DESCRIPTION, DCMHEADER_REQUESTING_PHYSICIAN, DCMHEADER_REFERRING_PHYSICIAN, \
	DCMHEADER_SERIES_DATE, DCMHEADER_SERIES_TIME, DCMHEADER_MODALITY, DCMHEADER_MANUFACTURER, \
	DCMHEADER_SERIES_DESCRIPTION, DCMHEADER_BODY_PART_EXAMINED, DCMHEADER_SEQUENCE_NAME, \
	DCMHEADER_PROTOCOL_NAME, DCMHEADER_SERIES_NUMBER, DCMHEADER_CARDIAC_NUMBER_OF_IMAGES, \
	DCMHEADER_IMAGES_IN_ACQUISITION, DCMHEADER_NUMBER_OF_TEMPORAL_POSITIONS, \
	DCMHEADER_NUMBER_OF_SLICES, DCMHEADER_NUMBER_OF_TIME_SLICES, DCMHEADER_SERIES_INSTANCE_UID, \
	DCMHEADER_SERIES_INSTANCE_UID, DCMHEADER_IMAGE_ORIENTATION_PATIENT, DCMHEADER_SERIES_TYPE, \
	DCMHEADER_OPERATORS_NAME, DCMHEADER_PERFORMED_PROCEDURE_STEP_DESCRIPTION, \
	DCMHEADER_ACQUISITION_DEVICE_PROCESSING_DESCRIPTION, DCMHEADER_CONTRAST_BOLUS_AGENT


ORTHANC_DEFAULT_ENCODING = 'utf-8'

ORTHANC_SERVER_ID = 'OrthancServerId'
ORTHANC_SERVER_RESOURCE = "Resource"
ORTHANC_SERVER_SOURCE = 'Source'
ORTHANC_SERVER_DICOM = 'DCM'

ORTHANC_CONFIG_SECTION_DICOMWEB = 'DicomWeb'
ORTHANC_CONFIG_SECTION_POSTGRES = 'PostgreSQL'
ORTHANC_CONFIG_SECTION_SONADOR = 'Sonador'
ORTHANC_CONFIG_SECTION_EXTRADICOMTAGS = 'ExtraMainDicomTags'


ORTHANC_MAINDICOM_TAGS_DEFAULT = {
	IMAGING_SERVER_RESOURCE_PATIENT: set((
		DCMHEADER_PATIENT_NAME, DCMHEADER_PATIENT_ID, DCMHEADER_PATIENT_BIRTHDATE, 
		DCMHEADER_PATIENT_SEX, DCMHEADER_PATIENT_OTHERIDS)),
	IMAGING_SERVER_RESOURCE_STUDY: set((DCMHEADER_STUDY_DATE, DCMHEADER_STUDY_TIME, DCMHEADER_STUDY_ID, 
		DCMHEADER_STUDY_DESCRIPTION, DCMHEADER_ACCESSION_NUMBER, DCMHEADER_STUDY_INSTANCE_UID,
		DCMHEADER_STUDY_INSTANCE_UID, DCMHEADER_REQUESTED_PROCEDURE_DESCRIPTION, 
		DCMHEADER_REQUESTING_PHYSICIAN, DCMHEADER_REFERRING_PHYSICIAN)),
	IMAGING_SERVER_RESOURCE_SERIES: set((
		DCMHEADER_SERIES_DATE, DCMHEADER_SERIES_TIME, DCMHEADER_MODALITY, DCMHEADER_MANUFACTURER,
		DCMHEADER_SERIES_DESCRIPTION, DCMHEADER_BODY_PART_EXAMINED, DCMHEADER_SEQUENCE_NAME,
		DCMHEADER_PROTOCOL_NAME, DCMHEADER_SERIES_NUMBER, DCMHEADER_CARDIAC_NUMBER_OF_IMAGES,
		DCMHEADER_IMAGES_IN_ACQUISITION, DCMHEADER_NUMBER_OF_TEMPORAL_POSITIONS,
		DCMHEADER_NUMBER_OF_SLICES, DCMHEADER_NUMBER_OF_TIME_SLICES, DCMHEADER_SERIES_INSTANCE_UID,
		DCMHEADER_SERIES_INSTANCE_UID, DCMHEADER_IMAGE_ORIENTATION_PATIENT, DCMHEADER_SERIES_TYPE,
		DCMHEADER_OPERATORS_NAME, DCMHEADER_PERFORMED_PROCEDURE_STEP_DESCRIPTION,
		DCMHEADER_ACQUISITION_DEVICE_PROCESSING_DESCRIPTION, DCMHEADER_CONTRAST_BOLUS_AGENT)),
}


# Sonador Cache Index Status Codes
SONADOR_CACHE_STATUS_CURRENT = 'current'
SONADOR_CACHE_STATUS_INCOMPLETE = 'incomplete'

# Sonador Event Types
SONADOR_RESOURCE_UPDATE_PATIENT = 'sonador-patient-update'
SONADOR_RESOURCE_UPDATE_STUDY = 'sonador-study-update'
SONADOR_RESOURCE_UPDATE_SERIES = 'sonador-series-update'
SONADOR_RESOURCE_DELETE_PATIENT = 'sonador-patient-delete'
SONADOR_RESOURCE_DELETE_STUDY = 'sonador-study-delete'
SONADOR_RESOURCE_DELETE_SERIES = 'sonador-series-delete'

# Sonador Cache Index Operations
SONADOR_CACHE_OPCODE_INDEX_RESOURCES = 'index-resources'
SONADOR_CACHE_OPCODE_INDEX_PATIENT = 'index-patient'
SONADOR_CACHE_OPCODE_INDEX_DELETE_PATIENT = 'index-delete-patient'
SONADOR_CACHE_OPCODE_INDEX_STUDY = 'index-study'
SONADOR_CACHE_OPCODE_INDEX_DELETE_STUDY = 'index-delete-study'
SONADOR_CACHE_OPCODE_INDEX_SERIES = 'index-series'
SONADOR_CACHE_OPCODE_INDEX_DELETE_SERIES = 'index-delete-series'

# Sonador Cache Response Codes
SONADOR_CACHE_COUNT_PATIENT = 'patient-count'
SONADOR_CACHE_COUNT_STUDY = 'study-count'
SONADOR_CACHE_COUNT_SERIES = 'series-count'

